---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _questions
  label: Questions
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - noticia
  - post
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - page
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
